# Generated by Django 5.0.3 on 2025-04-11 09:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='media/profile_images'), upload_to='profile_images/'),
        ),
    ]
